version: '2'
services:
  db:
    image: mariadb:latest
    # networks:
    #   main:
    #     aliases:
    #       - db
    volumes:
      - "/var/lib/mysql"
      - "./db/init:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    # networks:
    #   main:
    #     aliases:
    #       - redis       

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
        - "1025:1025"
        - "1080:1080"

  fpm:
    depends_on:
      - mailcatcher
      - db
      - elasticsearch
    # networks:
    #   main:
    #     aliases:
    #       - fpm
    build: ./fpm
    restart: always 
    volumes:
      - "./www:/var/www/html"
      - "./www2/wordpress:/var/www2/html"
      - "./fpm/customized.ini:/usr/local/etc/php/conf.d/customized.ini"      
  http:
    depends_on:
      - fpm
    # networks:
    #   main:
    #     aliases:
    #       - nginx
    image: nmarus/nginx-full
    volumes:
      - "./conf/http/nginx.conf:/etc/nginx/nginx.conf"
      - "./conf/http/conf.d:/etc/nginx/conf.d"
      - "./www:/var/www/html"
      - "./www2/wordpress:/var/www2/html"
    ports:
      - "8080:80"

  https:
    depends_on:
      - varnish
      - http
    # networks:
    #   main:
    #     aliases:
    #       - https
    image: nmarus/nginx-full
    ports:
      - "443:443"
    volumes:
      - "./conf/https/nginx.conf:/etc/nginx/nginx.conf"
      - "./conf/https/conf.d:/etc/nginx/conf.d"
      - "./conf/certs:/etc/nginx/ssl"

  varnish:
    image: eeacms/varnish
    depends_on:
      - http
    # networks:
    #   main:
    #     aliases:
    #       - varnish 
    ports:
      - "80:6081"
      - "6085:6085"
    volumes:
      - "./conf/varnish/varnish.vcl:/etc/varnish/conf.d/varnish.vcl"
    environment:
      BACKENDS: "http"
      BACKENDS_PORT: "80"
      BACKENDS_PROBE_INTERVAL: "3s"
      BACKENDS_PROBE_TIMEOUT: "1s"
      BACKENDS_PROBE_WINDOW: "3"
      BACKENDS_PROBE_THRESHOLD: "2"
      DASHBOARD_USER: "admin"
      DASHBOARD_PASSWORD: "admin"
      DASHBOARD_SERVERS: "varnish"

  phpmyadmin:
    depends_on:
      - db  
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    ports:
     - 8888:80
    volumes:
     - /sessions

  elasticsearch:
    image: elasticsearch
    environment:
      - discovery.type=single-node
    # networks:
    #   main:
    #     aliases:
    #       - elasticsearch

# networks:
#   main: