version: '2'
services:
  db:
    image: mariadb:latest
    volumes:
      - "/var/lib/mysql"
      - "./db/init:/docker-entrypoint-initdb.d"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf        

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
        - "1025:1025"
        - "1080:1080"

  fpm:
    depends_on:
      - mailcatcher
      - db
      - elasticsearch
    build: ./fpm
    restart: always 
    volumes:
      - "./www:/var/www/html"
      - "./www2/wordpress:/var/www2/html"
      - "./fpm/customized.ini:/usr/local/etc/php/conf.d/customized.ini"
  nginx:
    depends_on:
      - db
      - redis
      - fpm
    image: nmarus/nginx-full
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./conf/nginx.conf.d:/etc/nginx/conf.d"
      - "./www:/var/www/html"
      - "./www2/wordpress:/var/www2/html"
    links:
      - db
      - redis
      - fpm
      - elasticsearch
    ports:
      - "80:80"
      - "443:443"
    restart: always

  phpmyadmin:
    depends_on:
      - db  
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions

  elasticsearch:
    image: elasticsearch
    environment:
      - discovery.type=single-node